# -*- coding: utf-8 -*-
"""Assignment 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15SOsSyO6T82dgr5M-1DNKyNoAFyicfHa
"""

print("Hello python")
print("Hello\
      python")
name="abc"
age=22
marks=88.78
print("The name of the person is",name,"whose age is",age,"and scored marks are",marks)
print("The name of the person is %s whose age is %d and scored marks are %f"%(name,age,marks))
print("The name of the person is %s whose age is %d and scored marks are %10.2f"%(name,age,marks))
a=154
b=34
print(a+b, b**2, a/b, a//b, a*b)